### ISSUE TITLE
Forage Finder not reseting post after multiple save uploads

### ISSUE THREAD

**Issue by Kaiser92** [rickselby/stardew-helpers#261]
When uploading 2nd or more save, the previous result still remains which may lead to absurdly long page.
To have separate result required the page to be reloaded each new upload.

Also, is displaying artifact spots, trash cans and their contents possible?
Thank you for the awesome work.

**Comment by rickselby** [comment]
Artifact spots change each time you hoe a tile, so it's not possible to predict those any more. There used to be a page for them before 1.5.

Trash cans can be seen on https://mouseypounds.github.io/stardew-predictor/ as they're tied to the seed.

I'll look at getting the forage page fixed soon!

**Comment by Kaiser92** [comment]
I've been using the [Map Predictor](https://www.nexusmods.com/stardewvalley/mods/6614?tab=posts) to search for artifact spots and their contents quite reliably but the interface is not as nice as yours. If you can incorporated it in, that would be quite swell :)
