### ISSUE TITLE
"Content Missing" for Emily on Summer 6

### ISSUE THREAD

**Issue by rossc719g** [rickselby/stardew-helpers#417]
Just stumbled on this one...
When looking up Emily's schedule for Summer 6, the tool displays "Content Missing", and then both the calendar, and the character icons disappear.  The only way I have found to make it start working again is to hit back in my browser.

**Comment by rickselby** [comment]
Thanks for reporting! I made a change to convert times to 12 hour format, but Emily leaves the saloon after midnight and the times are stored as `2430` which breaks my conversions. I'll get that fixed shortly.

**Comment by rossc719g** [comment]
Thanks!
